language: python
python:
- 3.6
- 3.5
- 3.4
- 2.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: santoshphilip
  password:
    secure: Ebj40sfCPui9uxEHjcKAlg1H5ULigVYTDBH3ojSY05ebO0D81CwEKp9PsmAqbysimv7YpEOPtGP5o0M5xxw7C272YgmyUrztRr4KWNrrnFi0bTjexM2B9i/F7padWZ/YX6rF5H0/cIKAaDyNQC8xMi3Kypl7nZh7Vva0aX7BNMTI9msRT/gGPR2IL9GaBah6II0VEpvqeSsFy1IVf7iElX24zxt44pmMGgSlza2JbO+DpzmHOgukTxBHpYv8zFDGVM61VwR+iPRXEKCb3j1qfg/qgV1hCDNtp5sMrqcs/9nhwKdMAbNMtKwq8umB06waGbzVUCNXSu4dlpu4CLb//WwJ+NZQqjZWMyeN+LRWkkgGDfhVbFUEnKknrsLTrBgJb8dVZaGjMNtXI1mD3lYnqZHizONcbKfKnxF6gx+ipEnkHUMKqaS6YraHoLy7kkDrG5Cp6ObeeE8nmyr0lUCOQrxJIrsLCsEeChQGwFRzC/UAYN51Ik8bqVCQLQoUFNVQaQMOvcsMnqYJkall4x/inRhyCR7hxpeW1/ZaOX3YwmA6qZqsjh0Ke10S3nATfHtzGSLiq1F+vHI/c+Ghp8lKvtdohN1vn3DO4yodzPNZ1Pf5d2W8ZSEBakQrhMGaJHiJZBELg7/xFGPaDgrGDOjx21lSDlHUFxz6x0qT3v6hRFw=
  on:
    tags: true
    repo: santoshphilip/pyclearsky
    python: 3.6
